dist: focal
language: node_js
node_js:
  - v22.20.0
env:
  matrix:
    - NODE_OPTIONS="--max-old-space-size=4196"
cache:
  directories:
    - node_modules
install:
  - npm install
before_install:
  - npm i -g npm@10.9.3
